// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  []byte         `json:"-"`
	Avatar    sql.NullString `json:"avatar"`
	Verified  sql.NullBool   `json:"verified"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type UserInvitation struct {
	Token  string    `json:"token"`
	UserID int64     `json:"userId"`
	Expiry time.Time `json:"expiry"`
}
