// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID         int64          `json:"id"`
	CustomerID int32          `json:"customerId"`
	ServiceID  uuid.UUID      `json:"serviceId"`
	UserID     sql.NullInt32  `json:"userId"`
	BrandID    int32          `json:"brandId"`
	Date       time.Time      `json:"date"`
	StatusID   int32          `json:"statusId"`
	Comment    sql.NullString `json:"comment"`
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
}

type BookingStatus struct {
	StatusID   int32  `json:"statusId"`
	StatusName string `json:"statusName"`
}

type Brand struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	PageUrl     string         `json:"pageUrl"`
	Description sql.NullString `json:"description"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Country     sql.NullString `json:"country"`
	State       sql.NullString `json:"state"`
	ZipCode     sql.NullString `json:"zipCode"`
	City        sql.NullString `json:"city"`
	Address     sql.NullString `json:"address"`
	LogoUrl     sql.NullString `json:"logoUrl"`
	BannerUrl   sql.NullString `json:"bannerUrl"`
	Currency    sql.NullString `json:"currency"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type BrandSocialLink struct {
	ID          int32          `json:"id"`
	BrandID     int32          `json:"brandId"`
	Platform    string         `json:"platform"`
	Url         string         `json:"url"`
	DisplayName sql.NullString `json:"displayName"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type BrandWorkingHour struct {
	ID        int32        `json:"id"`
	BrandID   int32        `json:"brandId"`
	DayOfWeek int32        `json:"dayOfWeek"`
	OpenTime  sql.NullTime `json:"openTime"`
	CloseTime sql.NullTime `json:"closeTime"`
	IsClosed  sql.NullBool `json:"isClosed"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

type Customer struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	Password    []byte         `json:"password"`
	PhoneNumber sql.NullString `json:"phoneNumber"`
	BrandID     int32          `json:"brandId"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type Role struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Level int32  `json:"level"`
}

type Service struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Duration    int64          `json:"duration"`
	BufferTime  sql.NullInt64  `json:"bufferTime"`
	Cost        sql.NullString `json:"cost"`
	IsVisible   bool           `json:"isVisible"`
	ImageUrl    sql.NullString `json:"imageUrl"`
	BrandID     int32          `json:"brandId"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type User struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  []byte         `json:"-"`
	Avatar    sql.NullString `json:"avatar"`
	Verified  bool           `json:"verified"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	BrandID   sql.NullInt32  `json:"brandId"`
	Role      string         `json:"role"`
}

type UserInvitation struct {
	Token  string    `json:"token"`
	UserID int64     `json:"userId"`
	Expiry time.Time `json:"expiry"`
}

type UserService struct {
	UserID    int64     `json:"userId"`
	ServiceID uuid.UUID `json:"serviceId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
