// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddBrandSocialLink(ctx context.Context, arg AddBrandSocialLinkParams) (*BrandSocialLink, error)
	AssignServiceToUser(ctx context.Context, arg AssignServiceToUserParams) error
	AssociateUserWithBrand(ctx context.Context, arg AssociateUserWithBrandParams) error
	CreateBooking(ctx context.Context, arg CreateBookingParams) (*Booking, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (*Brand, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (*Customer, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (*Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) error
	DeleteBooking(ctx context.Context, arg DeleteBookingParams) error
	DeleteBrandSocialLink(ctx context.Context, arg DeleteBrandSocialLinkParams) error
	DeleteCustomer(ctx context.Context, id int64) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserInvitation(ctx context.Context, userID int64) error
	GetBookingByID(ctx context.Context, arg GetBookingByIDParams) (*GetBookingByIDRow, error)
	GetBookingsByBrand(ctx context.Context, arg GetBookingsByBrandParams) ([]*GetBookingsByBrandRow, error)
	GetBookingsByDateRange(ctx context.Context, arg GetBookingsByDateRangeParams) ([]*GetBookingsByDateRangeRow, error)
	GetBrandById(ctx context.Context, id int32) (*Brand, error)
	GetBrandByUrl(ctx context.Context, pageUrl string) (string, error)
	GetBrandProfile(ctx context.Context, id int32) (*GetBrandProfileRow, error)
	GetBrandUsers(ctx context.Context, brandID sql.NullInt32) ([]*User, error)
	GetBrandWorkingHours(ctx context.Context, brandID int32) ([]*BrandWorkingHour, error)
	GetCustomerBookings(ctx context.Context, arg GetCustomerBookingsParams) ([]*GetCustomerBookingsRow, error)
	GetCustomerByEmail(ctx context.Context, email string) (*Customer, error)
	GetCustomerById(ctx context.Context, id int64) (*Customer, error)
	GetService(ctx context.Context, id uuid.UUID) (*Service, error)
	GetUserBookingsByDateRange(ctx context.Context, arg GetUserBookingsByDateRangeParams) ([]*GetUserBookingsByDateRangeRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserById(ctx context.Context, id int64) (*User, error)
	GetUserFromInvitation(ctx context.Context, token string) (int64, error)
	GetUsersByBrand(ctx context.Context, brandID sql.NullInt32) ([]*User, error)
	ListServices(ctx context.Context, brandID int32) ([]*Service, error)
	ListUserServices(ctx context.Context, userID int64) ([]*Service, error)
	ListVisibleServices(ctx context.Context, brandID int32) ([]*Service, error)
	RemoveServiceFromUser(ctx context.Context, arg RemoveServiceFromUserParams) error
	UpdateBookingDetails(ctx context.Context, arg UpdateBookingDetailsParams) (*Booking, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (*Booking, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (*Brand, error)
	UpdateBrandPartial(ctx context.Context, arg UpdateBrandPartialParams) (*Brand, error)
	UpdateBrandWorkingHours(ctx context.Context, arg UpdateBrandWorkingHoursParams) (*BrandWorkingHour, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (*Service, error)
	ValidateUsersCount(ctx context.Context, arg ValidateUsersCountParams) (int64, error)
	VerifyUser(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
